data:
  raw_file_name: "Dementia Prediction Dataset.csv"
  drive_url: "https://drive.google.com/file/d/19mKGPNFb35kG__3Eihazyv5O69ZUxDcF/view?usp=drive_link"

paths:
  raw_data: "artifacts/data/raw_data.csv"
  cleaned_data: "artifacts/data/cleaned_data.csv"
  X_train: "artifacts/data/X_train.csv"
  X_test: "artifacts/data/X_test.csv"
  y_train: "artifacts/data/y_train.csv"
  y_test: "artifacts/data/y_test.csv"
  preprocessor_path: "artifacts/preprocessor/preprocessor.joblib"
  model_path: "models/stacked_model.joblib"

model_params:
  test_size: 0.2
  random_state: 42
  smote_random_state: 42
  classification_threshold: 0.3

  xgb_params:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.06
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: 'logloss'
    use_label_encoder: False
  lgb_params:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.06
  cat_params:
    iterations: 200
    depth: 6
    learning_rate: 0.06
    verbose: 0
  rf_params:
    n_estimators: 300
    max_depth: 12
    class_weight: 'balanced'
  final_estimator_params:
    max_iter: 500
    class_weight: 'balanced'

features:
  target: 'DEMENTED'

  selected_columns:
    - 'NACCID'
    - 'VISITYR'
    - 'BIRTHMO'
    - 'BIRTHYR'
    - 'SEX'
    - 'EDUC'
    - 'MARISTAT'
    - 'NACCLIVS'
    - 'INDEPEND'
    - 'NACCFAM'
    - 'NACCMOM'
    - 'NACCDAD'
    - 'TOBAC30'
    - 'TOBAC100'
    - 'ALCOCCAS'
    - 'ALCFREQ'
    - 'CBSTROKE'
    - 'HATTYEAR'
    - 'CVHATT'
    - 'DIABETES'
    - 'HYPERTEN'
    - 'DEP2YRS'
    - 'ANXIETY'
    - 'HEARING'
    - 'DEMENTED'

  binary_features:
    - 'SEX'
    - 'DIABETES'
    - 'HEARING'
    - 'TOBAC30'
    - 'TOBAC100'
    - 'CBSTROKE'
    - 'CVHATT'
    - 'HYPERTEN'
    - 'DEP2YRS'
    - 'ANXIETY'
    - 'ALCOCCAS'
    - 'ALCFREQ'
    - 'NACCFAM'
    - 'NACCMOM'
    - 'NACCDAD'

  categorical_features: ['MARISTAT', 'NACCLIVS', 'INDEPEND']
  continuous_features: ['AGE','EDUC']